name: Sync Main to Production

on:
  release:
    types: [published]

jobs:
  sync-to-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge main into production
        run: |
          git checkout production
          git merge main --no-edit

      - name: Push to production
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.OST_PRODUCTION_PUSH_PAT }}@github.com/${{ github.repository }}
          git push origin production
